name = "todo-service"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "todoservice.sanjaysingh.net", custom_domain = true }
]
workers_dev = false
preview_urls = false

[vars]
AUTH_SERVICE_URL = "https://authservice.sanjaysingh.net"

[[kv_namespaces]]
binding = "TODO_KV"
id = "411d1258d98a48f2928d51f2dc3657ee"